### ISSUE TITLE
Feedback on page: /payment/paypal-payments-pro.html

### ISSUE THREAD

**Issue by shiveshdaffodil** [magento/merchdocs#1037]
PayPal Payments Pro for credit/debit card does not display when merchant country is UK, while it works well when Merchant country is US. Can anyone help me to show pay pal pro credit/debit card payment method for UK

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation, and is instead a bug. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/).

**Recommended**! To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). Thanks for taking the time to create a GitHub issue for docs improvement!
