### ISSUE TITLE
Feedback on page: /system/data-advanced-price.html

### ISSUE THREAD

**Issue by lollicupgithub** [magento/merchdocs#1045]
How can assign the Magento advanced price product wholesales price(Local) to specific customer? 
![Magento_product_AdvancedPrice_WholesalesPrice](https://user-images.githubusercontent.com/36867251/107438521-73ee8a80-6ae5-11eb-976c-2d3051770436.JPG)
![Magento_Customer_Profile](https://user-images.githubusercontent.com/36867251/107438707-ccbe2300-6ae5-11eb-8ee8-8aa35aacdbf8.JPG)

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation.

To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
