### ISSUE TITLE
Avalara Tax  Plugin- Address Validation cannot complete check out the process. Please wait and order confirmation is not appeared.

### ISSUE THREAD

**Issue by lollicupgithub** [magento/merchdocs#1046]
Avalara Tax  Plugin version 2.1.8 Magento 2.3.4 ,  Order check out process cannot complete when enable the avalara tax plugin and address validation.
![Avatax setting](https://user-images.githubusercontent.com/36867251/107439837-8ff32b80-6ae7-11eb-8819-747cd3cc0b69.JPG)
![Avatax Address Validation](https://user-images.githubusercontent.com/36867251/107439844-92558580-6ae7-11eb-8827-603d270ebacf.JPG)
![Magento check out](https://user-images.githubusercontent.com/36867251/107439850-941f4900-6ae7-11eb-869c-93a4ce87f70f.JPG)
![Magento check out-please wait](https://user-images.githubusercontent.com/36867251/107439854-95e90c80-6ae7-11eb-8910-d9af964eee4e.JPG)

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
