### ISSUE TITLE
Feedback on page: /stores/attributes-customer-address.html

### ISSUE THREAD

**Issue by shekar800** [magento/merchdocs#1107]
Created new customer address attribute as dropdown type and displayed in front end as well. When we enter any address from address book and save it is saving the correct value. But when we do same from checkout  not storing correct value in DB. Every time it is storing as 0 in DB

Link: https://docs.magento.com/user-guide/stores/attributes-customer-address.html

**Comment by dshevtsov** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!

**Comment by dshevtsov** [comment]
@shekar800 
Thank you for taking on this PR/issue. If you are still interested in working on this topic, please let us know your progress. Thanks for taking the time to help improve the documentation!
