### ISSUE TITLE
How to edit the e-mail variables? - Feedback on page: /marketing/variables-reference.html

### ISSUE THREAD

**Issue by Eddcapone** [magento/merchdocs#1202]
I am facing the following problem. I have to change the customer create form so that we have two checkboxes for the prefix.
One for male and one for female. If the user does not select any of them, because he does not identify as a female or male, then we just like to show a message like "Good day Bastian Schweinsteiger". Currently it just shows "Bastian Schweinsteiger".
If the user selected male, then we would like to just show "Mr. Schweinsteiger"

How can we change this? There is not enough information in the documentation about how to modify the variables.

**Comment by erikmarr** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!

**Comment by Eddcapone** [comment]
@erikmarr Hello I don't understand how this is not related to the documentation. I address the problem that there is not enough information to understand the variables.
