### ISSUE TITLE
Feedback on page: /marketing/gift-registries.html

### ISSUE THREAD

**Issue by abdchandu** [magento/merchdocs#1490]
Observed the Shipping address is passing empty when user adds item to the cart from the Gift registries.

![Gift registry issue](https://user-images.githubusercontent.com/35223983/132491422-19e4eda2-2fcb-4c83-a90a-fa50975d13a2.gif)

Steps to replicate the issue:

1. Create Gift registries with products and provide the mandatory field details
2. Share the Gift registry to the user
3. Click on the link received and items added to the cart 
4. Navigate to the checkout page and observe the Shipping address
Actual result: Shipping address is passing empty when user adds item to the cart from the Gift registries.

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Commerce developer documentation. To get answers to your questions, check the [Adobe Commerce Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Adobe Commerce issues with code, see the [Adobe Commerce GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Adobe Commerce features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
