### ISSUE TITLE
Feedback on page: /reports/advanced-reporting.html

### ISSUE THREAD

**Issue by ayekannansp** [magento/merchdocs#1529]
![image](https://user-images.githubusercontent.com/72075998/134761452-d80da435-1a5a-4e9a-b272-da9efc1afd6b.png)
For magento2(2.2.10), I have gone through all the steps provided in magento2 official documentation [here](https://docs.magento.com/user-guide/reports/advanced-reporting.html). But no luck. It takes me to the above page. Please help me with that if anyone can?

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Commerce developer documentation.

However, if you do find out there is something missing or wrong in our documentation, please create an issue with more details.

To get answers to your questions, check the [Adobe Commerce Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Adobe Commerce issues with code, see the [Adobe Commerce GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Adobe Commerce features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
