### ISSUE TITLE
Feedback on page: /cms/dynamic-blocks.html

### ISSUE THREAD

**Issue by SherryElric** [magento/merchdocs#1628]
The JS in dynamic blocks  can not run

Simple test code
<script>
console.log('test');
</script>

**Comment by dshevtsov** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to documentation. To get answers to your questions, check the [Adobe Commerce Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Adobe Commerce issues with code, see the [Adobe Commerce GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Adobe Commerce features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
