### ISSUE TITLE
Paypal PRO: Session issue - Feedback on page: /payment/paypal-payments-standard.html

### ISSUE THREAD

**Issue by cmarra** [magento/merchdocs#1639]
https://docs.magento.com/user-guide/payment/paypal-payments-standard.html

Good evening, I open this report because we have found some anomalies regarding payments with Paypal Pro. Our customer uses the Magento 2 platform with the official Paypal plugin included by default in the Magento installation, specifically the version of Magento used is the 2.4.2. The problem seems to be related to the Magento checkout session, the user pays using Paypal Pro, the order is processed correctly and the payment is successful but Paypal redirects the user to a white page of Magento, the problem would seem be related to this file MAGENTO_ROOT / vendor / magento / module-paypal / Controller / Hostedpro / ReturnAction.php 

Waiting for your feedback.

Christian

**Comment by dshevtsov** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to documentation. To get answers to your questions, check the [Adobe Commerce Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Adobe Commerce issues with code, see the [Adobe Commerce GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Adobe Commerce features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
