### ISSUE TITLE
Feedback on page: /catalog/inventory-backorders.html

### ISSUE THREAD

**Issue by royfungbhi** [magento/merchdocs#1642]
https://docs.magento.com/user-guide/catalog/inventory-backorders.html

the out of stock threshold doesn't work and I am on Magento 2.3.3.  If I put in a negative number per this article, after I clicked save, the number will revert back to 0.

**Comment by dshevtsov** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to documentation. To get answers to your questions, check the [Adobe Commerce Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Adobe Commerce issues with code, see the [Adobe Commerce GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Adobe Commerce features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
