### ISSUE TITLE
Feedback on page: /configuration/customers/reward-points.html

### ISSUE THREAD

**Issue by umeshkdm** [magento/merchdocs#218]
reward point option not showing in my panel..I'm using 2.3.3 Magento version. is there any extension that has to add or Magento have a default option for reward point.?

https://user-images.githubusercontent.com/58258211/71572636-162bf880-2b06-11ea-880e-e4bde6f832bf.png

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento Docs documentation. To get this fixed contact [Magento Support](https://support.magento.com/hc/en-us/articles/360000913794-Magento-Help-Center-User-Guide#support-tickets)---They should be able to help you with this! Let us know if you have anymore questions.
--
