### ISSUE TITLE
Cannot get passed step 4 in the Amazon Store setup. 

### ISSUE THREAD

**Issue by riprod** [magento/merchdocs#231]
It gets to step 4, Preview Listings  smoothly and then the NEXT button is no longer clickable.

**Comment by hickskenh** [comment]
this is most likely a support issue, not a doc issue.  checking with Product Manager

**Comment by hickskenh** [comment]
@riprod  Apologies for the slow response.  I talked to one of the channels quality engineers to confirm that the Next button should be active throughout the entire onboarding process, since you can save your progress as you move through the steps. This appears to be a support issue and not a docs issue.  You can contact the Channels team at channels@adobe.com. I am closing this ticket, but if you find that i need to add a note or correction, you can open another issue after you talk to the channels team.
