### ISSUE TITLE
Feedback on page: /configuration/customers/customer-configuration.html

### ISSUE THREAD

**Issue by Safegear** [magento/merchdocs#426]
I set SHOW COMPANY as required and it's not asked the create account login page. 

I set SHOW VAT NUMBER as required and it is askde on the create account login page.

![image](https://user-images.githubusercontent.com/32866777/77746778-c1711e80-701d-11ea-8a14-1866bb2cc8d2.png)

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, contact [Magento Support](https://support.magento.com/hc/en-us/articles/360000913794-Magento-Help-Center-User-Guide#support-tickets)---They should be able to help you with this! Let us know if you have any more questions.

**Comment by Safegear** [comment]
Thank you, I will do.
