### ISSUE TITLE
Feedback on page: /catalog/product-fields-autogenerated.html

### ISSUE THREAD

**Issue by Safegear** [magento/merchdocs#443]
Hello, 

In order to create the Meta Title , Meta Keywords , Meta Description

We would like to use the "category" in which the product is. 

Is there any way to set this field enclosed?

Thank you?

**Comment by meker12** [comment]
@Safegear
Thank you for your feedback! It doesn't seem like your issue is a documentation issue. To get answers to your questions, see the following resources:
- [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/)
- [Stack Exchange](https://community.magento.com/). 
- To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2).
- To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). 

Thanks for taking the time to create a GitHub issue for docs improvement!

**Comment by meker12** [comment]
We are closing this issue. If you have a specific request to change or update the documentation, please feel free to re-open and provide details for the change.
