### ISSUE TITLE
Feedback on page: /system/web-setup-extension-manager.html

### ISSUE THREAD

**Issue by wadrajab** [magento/merchdocs#543]
It always shows 0 Extensions for me although I downloaded many :( what to do SEND HELP

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation, but is instead an extension issue. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
--

**Comment by jeff-matthews** [comment]
Unfortunately, the behavior you describe is due to a known issue in Magento 2.3.x @wadrajab. 

See https://support.magento.com/hc/en-us/articles/360043980352?_ga=2.201008429.2061030600.1591619027-634562557.1588612298
