### ISSUE TITLE
Feedback on Dashboard "Lifetime Sales" in Volume and in Currency

### ISSUE THREAD

**Issue by frahimm** [magento/merchdocs#780]
Hi,

We have recently started using Magento OpenSource 2.3.5 version. Very soon we will be launching our own ecommerce website but we are facing some massive issues in the version.

1. Dashboard - Life Time Sales in volume and in currency does not 'update'. It shows 0 even after placing so many orders. 
2. Credit Note - For creating refund, we need to create credit note but it does not show 'add credit note' in any menu pages. We have cross checked with youtube videos but in those versions it is showing add credit note but not in ours. 
3. Reporting - Does not work.

**Comment by ccondra** [comment]
Hi @frahimm, 
The issues you that describe don't seem to be related to our documentation. Because we do not provide support through this channel, I am going to close this ticket. However, for help with returns, see [Credit Memos](https://docs.magento.com/user-guide/sales/credit-memos.html). Also, because our user guide is based on the latest version of Magento Commerce, it includes some features that aren't available in Open Source. (Features that are not available in Open Source are marked with an orange (Magento Commerce) or blue (B2B) Magento logo).  I hope this helps!  Thank you -- Claire
