### ISSUE TITLE
Feedback on page: /marketing/url-rewrite-update-all.html

### ISSUE THREAD

**Issue by keke996** [magento/merchdocs#807]
when i save,
page display
![EF MXX1YA0 ~4ZDG_VG4LT1](https://user-images.githubusercontent.com/29771494/96143806-0dda6800-0f36-11eb-820c-e0262e8a2797.png)
But, items always is 1,din't change?
What's wrong?

**Comment by keke996** [comment]
I flow user-guide/v2.3/marketing/url-rewrite-update-all.html.
And cron is working.
But ,Why items always is 1,never change?

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation.

To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests).

We also suggest asking in the #general channel in Magento Community Engineering Slack about this issue to see if others have info!

Thanks for taking the time to create a GitHub issue for docs improvement!
