### ISSUE TITLE
CVV with initial value Zero says invalid CVV in Magento 2.2.7

### ISSUE THREAD

**Issue by rutwikdatatech** [magento/merchdocs#834]
Hello,

I am using Magento 2.2.7 and Brain Tree for Credit Card checkout payment method. But when I enters CVV starts with zero, it says Invalid CVV, for rest of the CVV its working fine.
Please help.

Thank You.

**Comment by erikmarr** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, contact [Magento Support](https://support.magento.com/hc/en-us/articles/360000913794-Magento-Help-Center-User-Guide#support-tickets)---They should be able to help you with this! Let us know if you have anymore questions.
