### ISSUE TITLE
Need help to get the value for attribute

### ISSUE THREAD

**Issue by ktlee95** [magento/merchdocs#838]
Hi, I have not seen dimension configuration(length, width, height) in the magento catalog settings. So i have created an attribute in the stores>attrbutes>product. After that i have add the attribute to my product.
![image](https://user-images.githubusercontent.com/19160574/98128166-89568600-1ef2-11eb-83be-1ae2dd50bb3c.png)
![image](https://user-images.githubusercontent.com/19160574/98128470-f0743a80-1ef2-11eb-8988-ab07d4090c1a.png)

However, in my php code(for shipping cost calculation), i was not able to get the value i enter for width, length, and height. I was able to log the label of my attribute, however i am not able to retrieve the value. I need retrieve those values for my shipping cost calculation.
```
 $info= $item->getProduct()->getResource()->getAttribute('dimensions_length')->getFrontendLabel();
 $this->_logger->log(100, $info);
```

I am beginner on magento and currently working on magento 2.4.0. Please help!!

**Comment by erikmarr** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, contact [Magento Support](https://support.magento.com/hc/en-us/articles/360000913794-Magento-Help-Center-User-Guide#support-tickets)---They should be able to help you with this! Let us know if you have anymore questions.
