### ISSUE TITLE
Update VAT configuration example to clarify Vat tax rate example

### ISSUE THREAD

**Issue by antonioglass** [magento/merchdocs#923]
On the Admin sidebar, go to Stores > Taxes > Tax Zones and Rates - this destination is wrong, the right would be Stores > Taxes > Tax Rules.

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by leslietilling** [comment]
The path change in Step 1 would not be correct. In looking more closely, it looks like the `Step 1` involves the confirmation of the needed tax class/rate in order to complete `Step 2` (which involves going to Taxes > Tax Rules) for creating the tax rule. I think the older tax class terminology needs clarification and the example should be an existing VAT tax rate, which would not be present by default. If the user does not already have an appropriate tax rate for the Vat tax rule, we should direct them to the topic for creating the tax rate.

**Comment by ZhovnirMaria** [comment]
@magento I am working on this
